export default {
  generateCard: '#wpforms-template-generate',
  generateButton: '.wpforms-template-generate',
  generateButtonsWrap: '#wpforms-template-generate .wpforms-template-buttons',
  generateBadge: '#wpforms-template-generate .wpforms-badge',
  builderPanel: '#wpforms-builder',
  aiPanel: '#wpforms-panel-ai-form',
  aiSidebar: '.wpforms-panel-sidebar',
  aiContentWrap: '.wpforms-panel-content-wrap',
  aiHeader: '.wpforms-ai-chat-header-title',
  emptyState: '.wpforms-panel-empty-state',
  promptInput: 'wpforms-ai-chat[mode="forms"] .wpforms-ai-chat-message-input textarea',
  promptInputBox: 'wpforms-ai-chat[mode="forms"] .wpforms-ai-chat-message-input',
  sendPrompt: 'wpforms-ai-chat[mode="forms"] .wpforms-ai-chat-send',
  questionBubble: '.wpforms-chat-item-question',
  answerBubble: '.wpforms-chat-item-answer',
  useFormButton: '.wpforms-ai-chat-use-form',
  previewTitle: '.wpforms-ai-form-generator-preview-title',
  previewPanel: '#wpforms-panel-ai-form .wpforms-panel-content',
  nameField: '#wpforms-generator-field-1',
  emailField: '#wpforms-generator-field-2',
  ratingField: '#wpforms-generator-field-3',
  npsField: '#wpforms-generator-field-4',
  likeField: '#wpforms-generator-field-5',
  improveField: '#wpforms-generator-field-6',
  sourceField: '#wpforms-generator-field-7',
  submitButton: '.wpforms-ai-form-generator-preview-submit',
  choicesField: '#wpforms-field-7',
  choicesFieldLabel: '#wpforms-field-7 .label-title .text',
  choicesOptionLabel: '#wpforms-field-option-7-label',
  choicesRow: '#wpforms-field-option-row-7-choices',
  choicesList: '#wpforms-field-option-7-choices-list',
  aiChoicesButton: '#wpforms-field-option-7-ai_modal_button',
  aiChoicesModal: '.wpforms-ai-choices-modal',
  aiChoicesInput: '.wpforms-ai-choices-modal textarea',
  aiChoicesSend: '.wpforms-ai-choices-modal .wpforms-ai-chat-send',
  aiChoicesInsert: '.wpforms-ai-choices-modal .wpforms-ai-chat-choices-insert',
};
