// AUTOGENERATED by authoring/brief-to-video.js — do not edit by hand.
import { defineChapter } from '/runtime/chapter-api.js';
import sel from './_selectors/hide-label.js';

export default defineChapter({
  slug: 'hide-label',
  title: 'Hide the field label',
  snapshot: 'builder-field-options-checkbox',
  chapter: 'hide-label',
  prep: [{ op: 'removeAdminBar' }, { op: 'removeBuilderCruft' }, { op: 'stripQuizEnabled' }, { op: 'activateFieldOptionGroup', fieldId: 7, group: 'advanced' }, { op: 'activateFieldOptionGroup', fieldId: 7, controlName: 'label_hide' }],
  steps: [
    {
      id: 'open-advanced-tab',
      label: 'Switch to the Advanced field options tab',
      do: 'clickOn',
      target: sel.openAdvancedTab,
      narration: 'hide-label-open-advanced-tab',
    },
    {
      id: 'toggle-hide-label',
      label: 'Toggle on Hide Label to drop the label from the rendered form',
      do: 'clickOn',
      target: sel.toggleHideLabel,
      after: [{ op: 'setHideLabel', fieldId: 7, hidden: true }],
      narration: 'hide-label-toggle-hide-label',
    },
  ],
});
