// AUTOGENERATED by authoring/brief-to-video.js — do not edit by hand.
// Provenance traces to snapshots/builder-field-options-checkbox/catalog.md.

export default {
  // snapshots/builder-field-options-checkbox/catalog.md#id--wpforms-field-option-advanced-7 (audit-rewrite: rect-zero → activateFieldOptionGroup advanced, anchor on group toggle)
  openAdvancedTab: '#wpforms-field-option-advanced-7 > .wpforms-field-option-group-toggle',
  // snapshots/builder-field-options-checkbox/catalog.md#id--wpforms-field-option-row-7-label_hide (audit-rewrite: rect-zero → activateFieldOptionGroup)
  toggleHideLabel: '#wpforms-field-option-row-7-label_hide',
};
